<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            ThemeManager\Middleware\DefaultParamsMiddleware::class => ThemeManager\Middleware\DefaultParamsMiddlewareFactory::class,
            UserManager\Handler\LogoutHandler::class => UserManager\Handler\LogoutHandlerFactory::class,
            UserManager\Middleware\IdentityMiddleware::class => UserManager\Middleware\IdentityMiddlewareFactory::class,
        ],
    ],
];
